/**
 * Release-owned Skill authoring guide, staged read-only at
 * /workspace/guides/skills.md: AIQSA's counterpart of a skill-creator.
 * It documents `save_skill` and the guest `aiqsa.mcp` client.
 */
export const WORKSPACE_SKILLS_GUIDANCE = [
  "# Script Skills",
  "",
  "Read this before building, changing or saving a Skill whose script does the work.",
  "",
  "## When",
  "- Make a script Skill for a repeatable data-collection or automation step the user will run again, by name or on a schedule. A one-off task needs no Skill.",
  "- The script collects and transforms deterministically; the model then analyses its short output. Keep judgement out of the script.",
  "",
  "## Layout",
  "- Build in /workspace/project/skills/<name>/ (lowercase, hyphens). That folder is what you save.",
  "- To change an existing Skill, first copy /workspace/.aiqsa/skills/<alias>/ there. The staged copy is read-only and replaced every run: never edit it.",
  "- Files: SKILL.md, an entry script (run.py), its lockfile, optional small helpers. UTF-8 text only, at most 1 MiB per file and 100 files. Never include virtualenvs, node_modules, wheels, caches, outputs or data dumps.",
  "",
  "## SKILL.md",
  "```",
  "---",
  "name: gitlab-failed-pipelines",
  "description: Collects the latest failed GitLab pipeline of a project with failed job logs and recent commits. Use when the user asks why a pipeline, build or CI run failed.",
  "compatibility: \"MCP: GitLab. Secrets: none. Needs Internet.\"",
  "---",
  "```",
  "- name: short and distinctive; a user message naming it exactly always keeps it available.",
  "- description: what it does and when to use it, in words the user would say. Automatic Skill selection reads only the name and this field.",
  "- compatibility (at most 500 characters): required MCP servers by display name, secret environment variable names (never values), Internet.",
  "- Body: the exact run command with its flags, path relative to the Skill folder (`uv run --script run.py --project group/app`), `--dry-run` for anything that writes, the inputs, the output contract (what stdout holds, which files are written), what each non-zero exit means and what to do, and what the model should analyse afterwards.",
  "",
  "## Dependencies",
  "- Prefer the standard library and preinstalled packages (pandas, matplotlib, openpyxl, python-docx, pdfplumber, playwright and others). Without Internet only these work.",
  "- Python: declare dependencies inline (PEP 723) with pinned versions:",
  "```",
  "# /// script",
  "# requires-python = \">=3.11\"",
  "# dependencies = [\"httpx==0.28.1\"]",
  "# ///",
  "```",
  "- Then `uv lock --script run.py` writes run.py.lock: keep it in the folder and relock after changing dependencies. Run with `uv run --script run.py`. The uv cache stays on this chat's disk, so later runs reuse it.",
  "- Node only when a library requires it: package.json with exact versions plus pnpm-lock.yaml; run `pnpm install --frozen-lockfile` in a writable copy, never save node_modules.",
  "",
  "## Secrets",
  "- Read credentials only from environment variables (`os.environ[\"GITLAB_TOKEN\"]`); /workspace/SECRETS.md lists the names. If one is missing, exit with a message naming the variable.",
  "- Never write a value into any file: save_skill refuses a folder that contains one. Never print or log values, auth headers or URLs with tokens; output masking is a safety net, not permission.",
  "",
  "## MCP tools from code",
  "```",
  "import aiqsa",
  "for tool in aiqsa.mcp.list_tools():",
  "    print(tool.name, tool.server, tool.tool)",
  "result = aiqsa.mcp.call(\"GitLab/list_pipelines\", {\"project_id\": \"group/app\", \"per_page\": 20})",
  "data = result.json()  # structured content, or the text parsed as JSON",
  "```",
  "- `import aiqsa` needs no dependency entry. From other languages: `aiqsa-mcp list` and `aiqsa-mcp call GitLab/list_pipelines --json '{...}'`; a failure prints JSON to stderr with a stable exit code.",
  "- Discover with list_tools() while building, then use exact names or \"<server>/<tool>\" in the script.",
  "- Works only inside a Workspace command of a personal chat with Internet on; Project chats get ProjectUnsupported. Agent runs with MCP Auto cannot list tools, but call() by exact name works.",
  "- Errors are typed (aiqsa.errors): InternetOff, McpOff, ProjectUnsupported, ToolUnavailable, InvalidArguments, AuthorizationRequired (the user must reconnect the server in AIQSA), BudgetExhausted, RateLimited, ToolError. Catch them and exit with a one-line reason.",
  "- Each run has a call budget (by default 200 calls, 4 at once, 10 per second): page with small requests, stop when you have enough, never call per item of a long list.",
  "- OutcomeUnknown or ResultUnsupported mean the call may have run: never repeat a write because of them; report and stop.",
  "- Results are not stored by AIQSA: reduce them in code and print a summary.",
  "",
  "## Writes",
  "- Make writes idempotent: read the target first (the last row, an existing id or marker) and skip what is already there, so a repeated or half-finished run never duplicates.",
  "- Give every writer `--dry-run`: print what would change and write nothing. Test with `--dry-run` first. A real write while testing needs the user's explicit go-ahead in this chat.",
  "",
  "## Output",
  "- stdout is for the model: a short summary of tens of lines (counts, key facts, file paths), never raw dumps.",
  "- Put large data in files under /workspace/project/out/ or in the target system, and print their paths.",
  "- Exit 0 on success. On failure exit non-zero with one line on stderr saying why.",
  "- Durable state between runs (cursors, last seen ids) belongs in the target system or is recomputed from it. The Workspace disk is not backed up and is deleted after retention; a scheduled task's new monthly chat carries only /workspace/project.",
  "",
  "## Test, then save",
  "- Save only when the user asked to create, save or change a Skill.",
  "- Run it once on real data (writers with `--dry-run`), show the user the result, fix and rerun until it works.",
  "- Then call save_skill with the folder and every file in it (list them with `find . -type f`): target \"new\" for a new Skill, or the alias of the user's Skill to save a new version on top of the version staged in this run. Another user's Skill is saved as the user's own copy. On a conflict, merge the returned current files and save again with the returned skillId and expectedVersion.",
  "- restoreRevision puts an earlier version back (0 lists the versions).",
  "- Tell the user that the card in the answer shows the changes and has Undo."
].join("\n");
