export const databaseRequiredTestFiles = [
  "lib/server/auth/adminDashboardQueries.test.ts",
  "lib/server/auth/adminRepository.test.ts",
  "lib/server/auth/oauthRepository.test.ts",
  "lib/server/auth/passwordRepository.test.ts",
  "lib/server/auth/registrationRepository.test.ts",
  "lib/server/chats/prismaRepository.test.ts",
  "lib/server/messages/prismaRepository.test.ts",
  "lib/server/memory/explicit/prismaExplicit.prisma.test.ts",
  "lib/server/memory/history/repository.prisma.test.ts",
  "lib/server/memory/lifecycle/prismaLifecycle.prisma.test.ts",
  "lib/server/memory/persistence/prismaPersistence.prisma.test.ts",
  "lib/server/memory/scopeLifecycle.prisma.test.ts",
  "lib/server/memory/sourceState.prisma.test.ts",
  "lib/server/memory/temporaryRetention.prisma.test.ts",
  "lib/server/memory/execution/prismaExecution.prisma.test.ts",
  "lib/server/memory/embedding/prismaEmbedding.prisma.test.ts",
  "lib/server/memory/coordinator/prismaRepository.prisma.test.ts",
  "lib/server/retention/prune.prisma.test.ts",
  "lib/server/runs/prismaRepository.test.ts",
  "lib/server/runs/preparingRun.prisma.test.ts",
  "lib/server/settings/prismaRepository.test.ts",
  "lib/server/uploads/defaultProcessing.prisma.test.ts"
] as const;
