import { randomUUID } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { inflateRawSync } from "node:zlib";
import { expect, test, type Locator, type Page, type TestInfo } from "@playwright/test";
import type { SkillDetail, SkillImportResponse } from "../../lib/contracts/skills";
import { writeZip } from "../../lib/server/artifacts/zip";
import { selectModel } from "./shell/composer";
import { runAccountMenuAction } from "./shell/page";
import { expectCenterUnobscured, expectNoHorizontalOverflow, expectWithinViewport } from "./support/layoutAssertions";
import { signInWithLocalToken } from "./support/localAuth";

test.setTimeout(180_000);
test.use({ locale: "en-US", contextOptions: { reducedMotion: "reduce" } });

type Upload = { name: string; mimeType: string; buffer: Buffer };
type ExportEntry = { path: string; bytes: Buffer; executable: boolean };

function markdown(name: string, description: string, instructions: string): Buffer {
  return Buffer.from(`---\nname: ${JSON.stringify(name)}\ndescription: ${description}\nlicense: MIT\nmetadata:\n  audience: synthetic\n---\n${instructions}\n`);
}

function remember(result: SkillImportResponse, owned: Set<string>): SkillImportResponse {
  for (const entry of result.results) if (entry.outcome !== "failed") owned.add(entry.skillId);
  return result;
}

async function cleanSkills(page: Page, owned: Set<string>): Promise<void> {
  const failures: number[] = [];
  for (const id of owned) {
    const response = await page.request.delete(`/api/me/skills/${id}`);
    if (!response.ok() && response.status() !== 404) failures.push(response.status());
  }
  expect(failures, "Every synthetic Skill is removed").toEqual([]);
}

async function detailFor(page: Page, id: string): Promise<SkillDetail> {
  const response = await page.request.get(`/api/me/skills/${id}`);
  expect(response.ok()).toBe(true);
  return ((await response.json()) as { skill: SkillDetail }).skill;
}

async function openLibrary(page: Page): Promise<Locator> {
  await runAccountMenuAction(page, "Assistants");
  await page.getByTestId("library-v2").getByRole("tab", { name: "Skill library", exact: true }).click();
  const library = page.getByTestId("skill-library-section");
  await expect(library).toBeVisible();
  return library;
}

async function openDetail(library: Locator, name: string): Promise<Locator> {
  const back = library.getByRole("button", { name: "Back to Skills", exact: true });
  if (await back.isVisible()) await back.click();
  await library.getByRole("searchbox", { name: "Search Skills" }).fill(name);
  await library.getByRole("button", { name: `Open ${name}`, exact: true }).click();
  const detail = library.getByRole("region", { name: "Skill detail", exact: true });
  await expect(detail.getByRole("heading", { name, exact: true })).toBeVisible();
  return detail;
}

async function importInBrowser(page: Page, library: Locator, upload: Upload | string, owned: Set<string>): Promise<SkillImportResponse> {
  const pending = page.waitForResponse((response) =>
    new URL(response.url()).pathname === "/api/me/skills/import" && response.request().method() === "POST");
  await library.getByLabel(typeof upload === "string" ? "Import Skill folder" : "Import Skill file", { exact: true })
    .setInputFiles(upload);
  const response = await pending;
  expect(response.status()).toBe(200);
  const result = remember(await response.json() as SkillImportResponse, owned);
  await expect(library.getByRole("status", { name: "Import results", exact: true })).toBeVisible();
  // An import is committed by this upload; it must not introduce a consent step.
  await expect(page.getByRole("alertdialog")).toHaveCount(0);
  await expect(library.getByRole("button", { name: "Import file", exact: true })).toBeEnabled();
  return result;
}

async function importViaApi(page: Page, buffer: Buffer, owned: Set<string>): Promise<SkillImportResponse> {
  const response = await page.request.post("/api/me/skills/import", {
    multipart: { file: { name: "skills.zip", mimeType: "application/zip", buffer } }
  });
  expect(response.status()).toBe(200);
  return remember(await response.json() as SkillImportResponse, owned);
}

async function downloadZip(page: Page, button: Locator): Promise<Buffer> {
  const pending = page.waitForEvent("download");
  await button.click();
  const download = await pending;
  expect(download.suggestedFilename()).toBe("skills.zip");
  expect(await download.failure()).toBeNull();
  const path = await download.path();
  expect(path).not.toBeNull();
  return readFile(path!);
}

// Inspect the downloaded ZIP independently of the application's import parser.
// These archives are generated by this test's authenticated server, never extracted to disk.
function exportEntries(zip: Buffer): ExportEntry[] {
  const end = zip.length - 22;
  expect(zip.readUInt32LE(end)).toBe(0x06054b50);
  const count = zip.readUInt16LE(end + 10);
  let cursor = zip.readUInt32LE(end + 16);
  const entries: ExportEntry[] = [];
  for (let index = 0; index < count; index += 1) {
    expect(zip.readUInt32LE(cursor)).toBe(0x02014b50);
    const method = zip.readUInt16LE(cursor + 10);
    expect([0, 8]).toContain(method);
    const nameLength = zip.readUInt16LE(cursor + 28);
    const path = zip.subarray(cursor + 46, cursor + 46 + nameLength).toString("utf8");
    const local = zip.readUInt32LE(cursor + 42);
    expect(zip.readUInt32LE(local)).toBe(0x04034b50);
    const dataStart = local + 30 + zip.readUInt16LE(local + 26) + zip.readUInt16LE(local + 28);
    const compressed = zip.subarray(dataStart, dataStart + zip.readUInt32LE(cursor + 20));
    const bytes = method === 0 ? compressed : inflateRawSync(compressed, { maxOutputLength: 8 * 1_024 * 1_024 });
    expect(bytes.length).toBe(zip.readUInt32LE(cursor + 24));
    entries.push({ path, bytes, executable: ((zip.readUInt32LE(cursor + 38) >>> 16) & 0o111) !== 0 });
    cursor += 46 + nameLength + zip.readUInt16LE(cursor + 30) + zip.readUInt16LE(cursor + 32);
  }
  expect(cursor).toBe(end);
  return entries;
}

async function captureResponsiveDetails(page: Page, detail: Locator, testInfo: TestInfo): Promise<void> {
  const viewports = [
    { name: "desktop", width: 1440, height: 900 },
    { name: "tablet-portrait", width: 834, height: 1194 },
    { name: "tablet-landscape", width: 1194, height: 834 },
    { name: "phone-portrait", width: 390, height: 844 },
    { name: "phone-landscape", width: 844, height: 390 }
  ];
  for (const theme of ["light", "dark"] as const) {
    await page.evaluate((value) => { document.documentElement.dataset.theme = value; }, theme);
    for (const viewport of viewports) {
      await page.setViewportSize({ width: viewport.width, height: viewport.height });
      const previewClose = detail.getByRole("button", { name: "Close file preview" });
      await previewClose.scrollIntoViewIfNeeded();
      await expectWithinViewport(page, previewClose);
      await expectCenterUnobscured(previewClose);
      await expectNoHorizontalOverflow(page);
      const path = testInfo.outputPath(`skills-bundles-${theme}-${viewport.name}.png`);
      await page.screenshot({ path, animations: "disabled" });
      await testInfo.attach(`Skills bundles · ${theme} · ${viewport.name}`, { path, contentType: "image/png" });
      // The lower action row must remain reachable even in a short landscape viewport.
      const exportButton = detail.getByRole("button", { name: "Export", exact: true });
      await exportButton.scrollIntoViewIfNeeded();
      await expectWithinViewport(page, exportButton);
      await expectCenterUnobscured(exportButton);
    }
  }
}

test("Skills bundles: SKILL.md updates and partial ZIP validation preserve successful imports", async ({ page }) => {
  await signInWithLocalToken(page);
  const owned = new Set<string>();
  const suffix = randomUUID().slice(0, 8);
  const name = `Field notes ${suffix}`;
  const description = `Review: ${"d".repeat(719)}`;
  const instructions = `${"Check the evidence before drawing conclusions.\n".repeat(800).slice(0, 34_342)}.`;
  const upload = { name: "SKILL.md", mimeType: "text/markdown", buffer: markdown(name, description, instructions) };
  try {
    const library = await openLibrary(page);
    const created = await importInBrowser(page, library, upload, owned);
    expect(created.results).toEqual([{ name, outcome: "created", skillId: expect.any(String) }]);
    const first = created.results[0]!;
    if (first.outcome === "failed") throw new Error("synthetic_skill_not_created");
    const original = await detailFor(page, first.skillId);
    expect(original.description).toHaveLength(727);
    expect(original.instructions).toBe(instructions);
    expect(original.instructions).toHaveLength(34_343);
    await openDetail(library, name);

    expect((await importInBrowser(page, library, upload, owned)).results)
      .toEqual([{ name, outcome: "unchanged", skillId: first.skillId }]);
    expect((await detailFor(page, first.skillId)).version).toBe(original.version);
    await expect(library.getByRole("status", { name: "Import results" })).toContainText("0 imported · 0 updated · 1 unchanged · 0 failed");

    const revisedInstructions = `${instructions}\n\nDouble-check dates.`;
    const updated = await importInBrowser(page, library, { ...upload, buffer: markdown(name, description, revisedInstructions) }, owned);
    expect(updated.results).toEqual([{ name, outcome: "updated", skillId: first.skillId }]);
    const revised = await detailFor(page, first.skillId);
    expect(revised.version).toBe(original.version + 1);
    expect(revised.instructions).toBe(revisedInstructions);
    expect((await importInBrowser(page, library, { ...upload, buffer: markdown(name, description, revisedInstructions) }, owned)).results[0]?.outcome).toBe("unchanged");
    expect((await detailFor(page, first.skillId)).version).toBe(revised.version);

    const goodName = `Release checklist ${suffix}`;
    const partial = await importInBrowser(page, library, {
      name: "mixed-skills.zip", mimeType: "application/zip", buffer: writeZip([
        { path: "valid/SKILL.md", bytes: markdown(goodName, "A concise release checklist.", "Check the release notes.") },
        { path: "invalid/SKILL.md", bytes: markdown(`Too long ${suffix}`, "d".repeat(1_025), "Preserve valid siblings.") },
        { path: "README.md", bytes: Buffer.from("Files outside Skill folders are ignored.") }
      ])
    }, owned);
    expect(partial.ignoredFiles).toBe(1);
    expect(partial.results).toHaveLength(2);
    expect(partial.results).toEqual(expect.arrayContaining([
      { name: goodName, outcome: "created", skillId: expect.any(String) },
      expect.objectContaining({ outcome: "failed", error: { code: "skill_field_too_long", field: "description", actual: 1_025, limit: 1_024 } })
    ]));
    const status = library.getByRole("status", { name: "Import results" });
    await expect(status).toContainText("1 imported · 0 updated · 0 unchanged · 1 failed");
    await expect(status).toContainText("description: 1,025 exceeds the limit of 1,024.");
    await expect(status).toContainText("1 files outside Skill folders skipped.");
    await openDetail(library, goodName);
  } finally {
    await cleanSkills(page, owned);
  }
});

test("Skills bundles: folder preview and export roundtrip preserve bytes and executable metadata across responsive layouts", async ({ page }, testInfo) => {
  await signInWithLocalToken(page);
  const owned = new Set<string>();
  const folder = await mkdtemp(join(tmpdir(), "aiqsa-skill-browser-"));
  const name = `Заметки команды ${randomUUID().slice(0, 8)}`;
  const instructions = "# Evidence review\n\nRead references/field-check.md before writing.\nSummarize the evidence, then list unresolved questions.";
  const files = [
    { path: "references/field-check.md", bytes: Buffer.from(`# Review checklist\n\n- Check dates.\n- Link sources.\n\nReference: https://example.test/${"evidence-".repeat(35)}\n`), executable: false },
    { path: "scripts/check.sh", bytes: Buffer.from("#!/bin/sh\nprintf 'synthetic check\\n'\n"), executable: true },
    { path: "assets/sample.png", bytes: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jV8sAAAAASUVORK5CYII=", "base64"), executable: false }
  ];
  try {
    await Promise.all(["references", "scripts", "assets"].map((path) => mkdir(join(folder, path))));
    await Promise.all([
      writeFile(join(folder, "SKILL.md"), markdown(name, "Review a small bundle of references and executable examples.", instructions)),
      ...files.map((file) => writeFile(join(folder, file.path), file.bytes))
    ]);
    const library = await openLibrary(page);
    const imported = await importInBrowser(page, library, folder, owned);
    expect(imported.results).toEqual([{ name, outcome: "created", skillId: expect.any(String) }]);
    const first = imported.results[0]!;
    if (first.outcome === "failed") throw new Error("synthetic_folder_not_created");
    const original = await detailFor(page, first.skillId);
    expect(original.bundle).toMatchObject({ fileCount: 3, hasExecutables: true });
    expect(original.files).toEqual(files.map((file) => ({ path: file.path, byteSize: file.bytes.length,
      executable: file.executable, kind: file.path.endsWith(".png") ? "binary" : "text" })).sort((a, b) => a.path.localeCompare(b.path)));
    let detail = await openDetail(library, name);
    const binaryRow = detail.locator(".v2-skill-files li").filter({ hasText: "assets/sample.png" });
    await expect(binaryRow).toContainText(`${files[2]!.bytes.length} bytes`);
    await expect(binaryRow).toContainText("Binary file");
    await expect(binaryRow.getByRole("button")).toHaveCount(0);
    await expect(detail.locator(".v2-skill-files li").filter({ hasText: "scripts/check.sh" })).toContainText("Executable");
    await detail.getByRole("button", { name: "View references/field-check.md", exact: true }).click();
    await expect(detail.locator('pre[aria-label="references/field-check.md"]')).toHaveText(files[0]!.bytes.toString());
    const binaryRead = await page.request.get(`/api/me/skills/${first.skillId}/files?path=assets%2Fsample.png`);
    expect(binaryRead.status()).toBe(400);
    expect(await binaryRead.json()).toEqual({ error: "skill_file_binary" });

    const exported = await downloadZip(page, detail.getByRole("button", { name: "Export", exact: true }));
    const entries = exportEntries(exported);
    expect(entries).toHaveLength(4);
    const source = entries.find((entry) => entry.path.endsWith("/SKILL.md"))!;
    expect(source).toBeTruthy();
    const alias = source.path.split("/")[0]!;
    expect(alias).toMatch(/^[a-z0-9]+(?:-[a-z0-9]+)*$/u);
    expect(source.bytes.toString()).toContain(`"name": ${JSON.stringify(alias)}`);
    expect(source.bytes.toString()).toContain(`"aiqsa-title":${JSON.stringify(name)}`);
    expect(source.bytes.toString()).toContain('"license": "MIT"');
    for (const file of files) expect(entries.find((entry) => entry.path === `${alias}/${file.path}`))
      .toEqual({ ...file, path: `${alias}/${file.path}` });

    const allEntries = exportEntries(await downloadZip(page, library.getByRole("button", { name: "Export all", exact: true })));
    for (const entry of entries) expect(allEntries).toContainEqual(entry);
    const replay = await importInBrowser(page, library, { name: "skills.zip", mimeType: "application/zip", buffer: exported }, owned);
    expect(replay.results).toEqual([{ name, outcome: "unchanged", skillId: first.skillId }]);
    expect((await detailFor(page, first.skillId)).version).toBe(original.version);

    expect((await page.request.delete(`/api/me/skills/${first.skillId}`)).ok()).toBe(true);
    owned.delete(first.skillId);
    // Recreate from the exported archive with no existing matching definition.
    await page.reload();
    const reopened = await openLibrary(page);
    const restored = await importInBrowser(page, reopened, { name: "skills.zip", mimeType: "application/zip", buffer: exported }, owned);
    expect(restored.results).toEqual([{ name, outcome: "created", skillId: expect.any(String) }]);
    const next = restored.results[0]!;
    if (next.outcome === "failed") throw new Error("synthetic_export_not_restored");
    expect(next.skillId).not.toBe(first.skillId);
    const roundtrip = await detailFor(page, next.skillId);
    expect(roundtrip).toMatchObject({ name, description: original.description, instructions, files: original.files, bundle: original.bundle });
    const secondExport = await page.request.get(`/api/me/skills/${next.skillId}/export`);
    expect(secondExport.ok()).toBe(true);
    expect(await secondExport.body()).toEqual(exported);

    detail = await openDetail(reopened, name);
    await reopened.getByRole("button", { name: "Dismiss import results" }).click();
    await detail.getByRole("button", { name: "View references/field-check.md", exact: true }).click();
    await expect(detail.locator('pre[aria-label="references/field-check.md"]')).toHaveText(files[0]!.bytes.toString());
    await captureResponsiveDetails(page, detail, testInfo);
  } finally {
    try { await cleanSkills(page, owned); } finally { await rm(folder, { recursive: true, force: true }); }
  }
});

test("Skills bundles: editor counters distinguish Unicode characters and UTF-8 bytes without losing the draft", async ({ page }) => {
  await signInWithLocalToken(page);
  const owned = new Set<string>();
  const validName = `Counter check ${randomUUID().slice(0, 8)}`;
  try {
    const library = await openLibrary(page);
    await library.getByRole("button", { name: "New Skill", exact: true }).click();
    const detail = library.getByRole("region", { name: "Skill detail", exact: true });
    const name = detail.getByRole("textbox", { name: "Name", exact: true });
    const description = detail.getByRole("textbox", { name: "Description", exact: true });
    const instructions = detail.getByRole("textbox", { name: "Instructions", exact: true });
    const create = detail.getByRole("button", { name: "Create Skill", exact: true });
    await name.fill("🧭".repeat(65));
    await description.fill("Keep the draft through field validation.");
    await instructions.fill("Check each field before saving.");
    await expect(name).toHaveValue("🧭".repeat(65));
    await expect(detail.getByText("65 / 64 characters", { exact: true })).toBeVisible();
    await create.click();
    await expect(name).toHaveAttribute("aria-invalid", "true");
    await expect(detail.getByRole("alert")).toHaveText("name: 65 exceeds the limit of 64.");

    await name.fill(validName);
    await description.fill("я".repeat(1_025));
    await expect(detail.getByText("1025 / 1024 characters", { exact: true })).toBeVisible();
    await create.click();
    await expect(description).toHaveAttribute("aria-invalid", "true");
    await expect(detail.getByRole("alert")).toHaveText("description: 1,025 exceeds the limit of 1,024.");
    await expect(name).toHaveValue(validName);

    await description.fill("A valid description after repair.");
    const oversized = `${"🧭".repeat(32_768)}x`;
    await instructions.fill(oversized);
    await expect(instructions).toHaveValue(oversized);
    await expect(detail.getByText("131,073 / 131,072 bytes", { exact: true })).toBeVisible();
    await create.click();
    await expect(instructions).toHaveAttribute("aria-invalid", "true");
    await expect(detail.getByRole("alert")).toHaveText("instructions: 131,073 exceeds the limit of 131,072.");
    await expect(description).toHaveValue("A valid description after repair.");

    const draft = { name: validName, description: "A valid description after repair.", instructions: "Keep the corrected draft." };
    for (const [data, expected] of [
      [{ ...draft, unknown: true }, { error: "skill_draft_invalid" }],
      [{ description: draft.description, instructions: draft.instructions }, { error: "skill_field_required", field: "name" }],
      [{ name: draft.name, instructions: draft.instructions }, { error: "skill_field_required", field: "description" }],
      [{ ...draft, description: "" }, { error: "skill_field_required", field: "description" }],
      [{ ...draft, instructions: oversized }, { error: "skill_field_too_long", field: "instructions", actual: 131_073, limit: 131_072 }]
    ] as const) {
      const response = await page.request.post("/api/me/skills", { data });
      expect(response.status()).toBe(400);
      expect(await response.json()).toEqual(expected);
    }
    await instructions.fill(draft.instructions);
    const pending = page.waitForResponse((response) =>
      new URL(response.url()).pathname === "/api/me/skills" && response.request().method() === "POST");
    await create.click();
    const response = await pending;
    expect(response.status()).toBe(201);
    const saved = (await response.json() as { skill: SkillDetail }).skill;
    owned.add(saved.id);
    expect(saved).toMatchObject(draft);
    await expect(library.getByText("Skill created.", { exact: true })).toBeVisible();
    await openDetail(library, validName);
  } finally {
    await cleanSkills(page, owned);
  }
});

test("Skills bundles: one 51-Skill ZIP supports 32 manual pins and an honest model-window budget", async ({ page }, testInfo) => {
  await signInWithLocalToken(page);
  const owned = new Set<string>();
  const prefix = `Pinned ${randomUUID().slice(0, 8)}`;
  const names = Array.from({ length: 51 }, (_, index) => `${prefix} ${String(index + 1).padStart(2, "0")}`);
  try {
    const imported = await importViaApi(page, writeZip(names.map((name, index) => ({
      path: `skill-${index}/SKILL.md`,
      bytes: markdown(name, "A repeatable evidence review step.", "Check the evidence and cite clear sources.\n".repeat(10).trim())
    }))), owned);
    expect(imported.ignoredFiles).toBe(0);
    expect(imported.results).toHaveLength(51);
    expect(imported.results.every((entry) => entry.outcome === "created")).toBe(true);
    const sample = imported.results[0]!;
    if (sample.outcome === "failed") throw new Error("synthetic_pinned_skill_not_created");
    const tokenEstimate = (await detailFor(page, sample.skillId)).instructionApproxTokens;
    expect(tokenEstimate).toBeGreaterThan(0);
    // Every fixture has the same instructions; use the server's public estimate as the UI oracle.
    const expectedTokens = tokenEstimate! * 32;
    const catalogResponse = await page.request.get("/api/me/catalog");
    expect(catalogResponse.ok()).toBe(true);
    const catalog = (await catalogResponse.json()).catalog as { models: Array<{
      providerFamily: string; upstreamModelId: string; provider: string; displayName: string; contextWindow?: number;
    }> };
    const model = catalog.models.find((entry) => entry.providerFamily === "fake" && entry.upstreamModelId === "fake-qsa");
    expect(model).toBeTruthy();
    expect(model!.contextWindow).toBeGreaterThan(0);
    await selectModel(page, model!.provider, model!.displayName);
    await page.getByRole("button", { name: "Add", exact: true }).click();
    await page.getByRole("menuitem", { name: /^Skills…/u }).click();
    const picker = page.getByRole("dialog", { name: "Skills", exact: true });
    await expectWithinViewport(page, picker);
    const search = page.waitForResponse((response) => {
      const url = new URL(response.url());
      return url.pathname === "/api/me/skills" && url.searchParams.get("q") === prefix;
    });
    await picker.getByRole("searchbox", { name: "Search Skills" }).fill(prefix);
    expect((await search).ok()).toBe(true);
    const available = picker.getByRole("list", { name: "Available Skills" });
    await expect(available.getByRole("button", { name: /^Open /u })).toHaveCount(30);
    await picker.getByRole("button", { name: "Load more", exact: true }).click();
    await expect(available.getByRole("button", { name: /^Open /u })).toHaveCount(51);
    for (const name of names.slice(0, 32)) await available.getByRole("button", { name: `Always use ${name}`, exact: true }).click({ timeout: 10_000 });
    const selection = picker.getByRole("region", { name: "Selected Skills", exact: true });
    const percentage = expectedTokens / model!.contextWindow! * 100;
    expect(percentage).toBeGreaterThan(25);
    await expect(selection).toContainText(`32 always included · ≈${expectedTokens.toLocaleString("en-US")} instruction tokens · ${percentage.toLocaleString("en-US", { maximumFractionDigits: 1 })}% of model window`);
    await expect(selection).toContainText("Pinned instructions use more than 25% of the model window.");
    await expect(selection).toContainText("Skill limit reached. Unpin a Skill to add another.");
    await expect(selection.getByRole("button", { name: /^Remove manual /u })).toHaveCount(32);
    const thirtyThird = available.getByRole("button", { name: `Always use ${names[32]}`, exact: true });
    await expect(thirtyThird).toBeDisabled();
    await selection.getByRole("button", { name: `Remove manual ${names[0]}`, exact: true }).click();
    await expect(selection).toContainText("31 always included · ≈");
    await expect(thirtyThird).toBeEnabled();
    await thirtyThird.click();
    await expect(selection.getByRole("listitem").last()).toContainText(`32. ${names[32]}`);
    await selection.locator("p").first().scrollIntoViewIfNeeded();
    await expectNoHorizontalOverflow(page);
    const path = testInfo.outputPath("skills-bundles-selection-budget.png");
    await page.screenshot({ path, animations: "disabled" });
    await testInfo.attach("Skills bundles · 32 pinned budget", { path, contentType: "image/png" });
    await picker.getByRole("button", { name: "Close Skills", exact: true }).click();
    const chip = page.getByRole("button", { name: "Change Skills mode", exact: true });
    await expect(chip).toHaveText("Skills: Auto · 32");
    await chip.click();
    await page.getByRole("menuitem", { name: /Skill library/ }).click();
    await expect(picker.getByRole("region", { name: "Selected Skills" })).toContainText("32 always included · ≈");
    await page.keyboard.press("Escape");
    await expect(chip).toBeFocused();
  } finally {
    await cleanSkills(page, owned);
  }
});
