export const MEMORY_RETRIEVAL_PIPELINE_VERSION = "memory-personal-retrieval-v18";
export const MEMORY_RETRIEVAL_FUSION_VERSION = "memory-retrieval-rrf-v11";
export const MEMORY_CONTEXT_PACKER_VERSION = "memory-context-packer-v12";

export const MEMORY_RETRIEVAL_RRF_K = 60;
export const MEMORY_RETRIEVAL_MAX_PRE_FUSION_CANDIDATES = 160;
export const MEMORY_RETRIEVAL_MAX_AGGREGATION_PRE_FUSION_CANDIDATES = 400;
export const MEMORY_RETRIEVAL_MAX_PARALLEL_LANES = 4;
export const MEMORY_RETRIEVAL_MAX_RANKED_CANDIDATES = 100;
export const MEMORY_RETRIEVAL_MAX_AGGREGATION_RANKED_CANDIDATES = 250;
export const MEMORY_RETRIEVAL_MAX_TARGETED_HISTORY_CANDIDATES = 60;
export const MEMORY_RETRIEVAL_MAX_TARGETED_RERANK_CANDIDATES = 80;
export const MEMORY_RETRIEVAL_MAX_AGGREGATION_HISTORY_CANDIDATES = 180;
export const MEMORY_RETRIEVAL_MAX_AGGREGATION_SOURCE_CHATS = 180;

// Candidate generation deliberately has no semantic similarity cutoff. The
// bounded nearest eligible candidates reach an optional ordering model; only
// server-side authority and lifecycle fences control admission.
export const MEMORY_RETRIEVAL_VECTOR_CANDIDATE_FLOOR = -1;
// Compatibility reranking is an ordering feature, not an admission gate. A
// calibrated optional junk floor may be introduced later, but is deliberately
// disabled until fixed-sample evidence supports one.
export const MEMORY_RETRIEVAL_RERANK_SCORE_FLOOR: number | null = null;
export const MEMORY_RETRIEVAL_SYNTHESIS_AUTHORITY_MULTIPLIER = 0.5;

export const MEMORY_RETRIEVAL_LANE_WEIGHTS = Object.freeze({
  FACT_ENTITY: 1.2,
  FACT_EXACT: 1.35,
  FACT_FTS_ENGLISH: 1,
  FACT_FTS_RUSSIAN: 1,
  FACT_FTS_SIMPLE: 1,
  FACT_TRIGRAM: 0.85,
  FACT_PROFILE: 1,
  FACT_RECENT: 0.65,
  FACT_TEMPORAL_FILTERED: 1.15,
  FACT_TEMPORAL_UNRESTRICTED: 0.3,
  FACT_VECTOR: 1,
  HISTORY_RECALL_EXACT: 1.35,
  HISTORY_DIGEST_FTS_SIMPLE: 1,
  HISTORY_RECALL_FTS_ENGLISH: 1,
  HISTORY_RECALL_FTS_RUSSIAN: 1,
  HISTORY_RECALL_FTS_SIMPLE: 1,
  HISTORY_RECALL_RECENT: 0.65,
  HISTORY_RECALL_TEMPORAL_FILTERED: 1.15,
  HISTORY_RECALL_TEMPORAL_UNRESTRICTED: 0.3,
  HISTORY_RECALL_TRIGRAM: 0.85,
  HISTORY_RECALL_VECTOR: 1
} as const);

export const MEMORY_CORE_CONTEXT_TARGET_TOKENS = 512;
// Adaptive reader-pack profiles. The legacy targeted/aggregation names remain
// aliases for their executable owners while the packer selects among all
// three profiles from the admitted retrieval semantics.
export const MEMORY_CONTEXT_TARGET_TOKENS = 6_000;
export const MEMORY_CONTEXT_HARD_CAP_TOKENS = 10_000;
export const MEMORY_CONTEXT_PAST_CHAT_TARGET_TOKENS = 10_000;
export const MEMORY_CONTEXT_PAST_CHAT_HARD_CAP_TOKENS = 16_000;
export const MEMORY_CONTEXT_COMPLEX_TARGET_TOKENS = 24_000;
export const MEMORY_CONTEXT_COMPLEX_HARD_CAP_TOKENS = 32_000;
export const MEMORY_CONTEXT_AGGREGATION_TARGET_TOKENS =
  MEMORY_CONTEXT_COMPLEX_TARGET_TOKENS;
export const MEMORY_CONTEXT_AGGREGATION_HARD_CAP_TOKENS =
  MEMORY_CONTEXT_COMPLEX_HARD_CAP_TOKENS;
export const MEMORY_CONTEXT_UNIVERSAL_HARD_CAP_TOKENS =
  MEMORY_CONTEXT_COMPLEX_HARD_CAP_TOKENS;
export const MEMORY_CORE_MAX_FACTS = 4;
export const MEMORY_CONTEXT_MAX_ITEMS = 20;
export const MEMORY_CONTEXT_AGGREGATION_MAX_ITEMS = 40;
export const MEMORY_CONTEXT_MAX_DYNAMIC_FACTS = 6;
export const MEMORY_CONTEXT_PROFILE_MAX_FACTS = 12;
export const MEMORY_CONTEXT_MAX_HISTORY_SNIPPETS = 20;
export const MEMORY_CONTEXT_MAX_SOURCE_CHATS = 20;
export const MEMORY_CONTEXT_AGGREGATION_MAX_HISTORY_SNIPPETS = 40;
export const MEMORY_CONTEXT_AGGREGATION_MAX_SOURCE_CHATS = 40;
export const MEMORY_CONTEXT_OVERVIEW_MAX_DIGESTS = 8;
export const MEMORY_CONTEXT_OVERVIEW_MAX_SOURCE_CHATS = 8;
export const MEMORY_CONTEXT_DYNAMIC_FACT_TARGET_TOKENS = 6_000;
export const MEMORY_CONTEXT_PROFILE_FACT_TARGET_TOKENS = 6_000;
export const MEMORY_CONTEXT_HISTORY_TARGET_TOKENS = 10_000;
export const MEMORY_CONTEXT_AGGREGATION_HISTORY_TARGET_TOKENS = 24_000;

export const MEMORY_RETRIEVAL_LANE_LIMITS = Object.freeze({
  FACT_PROFILE: 20,
  FACT_EXACT: 8,
  FACT_ENTITY: 12,
  FACT_FTS_ENGLISH: 12,
  FACT_FTS_RUSSIAN: 12,
  FACT_FTS_SIMPLE: 12,
  FACT_TRIGRAM: 8,
  FACT_RECENT: 4,
  FACT_TEMPORAL_FILTERED: 12,
  FACT_TEMPORAL_UNRESTRICTED: 4,
  FACT_VECTOR: 12,
  HISTORY_RECALL_EXACT: 12,
  HISTORY_DIGEST_FTS_SIMPLE: 30,
  HISTORY_RECALL_FTS_ENGLISH: 30,
  HISTORY_RECALL_FTS_RUSSIAN: 30,
  HISTORY_RECALL_FTS_SIMPLE: 30,
  HISTORY_RECALL_RECENT: 12,
  HISTORY_RECALL_TEMPORAL_FILTERED: 24,
  HISTORY_RECALL_TEMPORAL_UNRESTRICTED: 8,
  HISTORY_RECALL_TRIGRAM: 20,
  HISTORY_RECALL_VECTOR: 60
} as const);

export const MEMORY_RETRIEVAL_AGGREGATION_HISTORY_LANE_LIMITS = Object.freeze({
  HISTORY_RECALL_EXACT: 8,
  HISTORY_RECALL_FTS_ENGLISH: 40,
  HISTORY_RECALL_FTS_RUSSIAN: 40,
  HISTORY_RECALL_FTS_SIMPLE: 40,
  HISTORY_RECALL_RECENT: 32,
  HISTORY_RECALL_TEMPORAL_FILTERED: 60,
  HISTORY_RECALL_TEMPORAL_UNRESTRICTED: 16,
  HISTORY_RECALL_TRIGRAM: 24,
  HISTORY_RECALL_VECTOR: 120
} as const);

export function memoryRetrievalLaneLimit(
  lane: MemoryRetrievalLane,
  aggregationRequested: boolean
): number {
  if (aggregationRequested && lane in MEMORY_RETRIEVAL_AGGREGATION_HISTORY_LANE_LIMITS) {
    return MEMORY_RETRIEVAL_AGGREGATION_HISTORY_LANE_LIMITS[
      lane as keyof typeof MEMORY_RETRIEVAL_AGGREGATION_HISTORY_LANE_LIMITS
    ];
  }
  return MEMORY_RETRIEVAL_LANE_LIMITS[lane];
}

export const MEMORY_RETRIEVAL_LANE_ORDER = Object.freeze([
  "FACT_PROFILE",
  "FACT_EXACT",
  "FACT_ENTITY",
  "FACT_TEMPORAL_FILTERED",
  "HISTORY_RECALL_EXACT",
  "HISTORY_RECALL_TEMPORAL_FILTERED",
  "HISTORY_DIGEST_FTS_SIMPLE",
  "FACT_FTS_SIMPLE",
  "FACT_FTS_ENGLISH",
  "FACT_FTS_RUSSIAN",
  "FACT_TRIGRAM",
  "HISTORY_RECALL_FTS_SIMPLE",
  "HISTORY_RECALL_FTS_ENGLISH",
  "HISTORY_RECALL_FTS_RUSSIAN",
  "HISTORY_RECALL_TRIGRAM",
  "FACT_VECTOR",
  "HISTORY_RECALL_VECTOR",
  "FACT_TEMPORAL_UNRESTRICTED",
  "HISTORY_RECALL_TEMPORAL_UNRESTRICTED",
  "FACT_RECENT",
  "HISTORY_RECALL_RECENT"
] as const);

export type MemoryRetrievalLane = (typeof MEMORY_RETRIEVAL_LANE_ORDER)[number];
