ALTER TABLE "ModelRun" ADD COLUMN "cachedInputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ModelRun" ADD COLUMN "cacheWriteInputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ModelRun" ADD COLUMN "totalTokens" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "UsageEvent" ADD COLUMN "cachedInputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UsageEvent" ADD COLUMN "cacheWriteInputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UsageEvent" ADD COLUMN "totalTokens" INTEGER NOT NULL DEFAULT 0;
