import type { MemoryUiLocale } from "@/lib/contracts/memory";

export const MEMORY_OPERATIONS_UI_COPY_KEYS = [
  "entry",
  "entryDescription",
  "title",
  "back",
  "intro",
  "maintenanceHeading",
  "maintenanceDescription",
  "rebuildLabel",
  "rebuildDescription",
  "reembedLabel",
  "reembedDescription",
  "redreamLabel",
  "redreamDescription",
  "clearHeading",
  "clearLabel",
  "clearDescription",
  "clearFence",
  "clearRetention",
  "clearFuture",
  "runAction",
  "available",
  "unavailable",
  "historyOff",
  "historyUnavailable",
  "embeddingUnavailable",
  "learningUnavailable",
  "consentRequired",
  "lexicalOnly",
  "servedGeneration",
  "confirmationTitle",
  "confirmationOperation",
  "confirmationRebuild",
  "confirmationReembed",
  "confirmationRedream",
  "confirmationClear",
  "confirmationCancel",
  "confirmationCommit",
  "admitting",
  "statusHeading",
  "clearStatusHeading",
  "rebuildStatusHeading",
  "progress",
  "reference",
  "updated",
  "lastAudit",
  "refresh",
  "cancelJob",
  "cancelling",
  "dismiss",
  "dismissReference",
  "statePending",
  "stateClearRunning",
  "stateRetry",
  "stateBlocked",
  "stateClearSucceeded",
  "stateQueued",
  "stateRebuildRunning",
  "stateWaitingConsent",
  "stateCatchingUp",
  "stateReady",
  "stateRebuildSucceeded",
  "stateFailed",
  "stateStale",
  "stateCancelled",
  "cancelBoundary",
  "errorGeneric",
  "errorStale",
  "errorConsent",
  "errorEmbedding",
  "errorInProgress",
  "errorConfirmation",
  "errorNotFound"
] as const;

export type MemoryOperationsUiCopyKey =
  (typeof MEMORY_OPERATIONS_UI_COPY_KEYS)[number];
type CopyLocale = Readonly<Record<MemoryOperationsUiCopyKey, string>>;

const EN = {
  entry: "History operations",
  entryDescription: "Rebuild indexes, refresh derived history, or clear the retained-history index.",
  title: "History operations",
  back: "Back to Memory settings",
  intro: "Maintain derived Memory history without changing raw chats or pretending background work has already finished.",
  maintenanceHeading: "Index maintenance",
  maintenanceDescription: "Each rebuild uses a shadow generation. The currently active index remains served until an atomic successful switch.",
  rebuildLabel: "Build or rebuild search index",
  rebuildDescription: "Recreate eligible lexical or hybrid search entries from the current safe source set and catch up before activation.",
  reembedLabel: "Re-embed history index",
  reembedDescription: "Create a qualified hybrid shadow with the currently selected embedding deployment.",
  redreamLabel: "Reprocess existing chats",
  redreamDescription: "Explicitly run provider-backed episode extraction over eligible retained chats. Source and suppression barriers still apply.",
  clearHeading: "Destructive history action",
  clearLabel: "Clear chat-history memory index",
  clearDescription: "Fence and purge rebuildable chat excerpts, episodes, and their search entries.",
  clearFence: "After admission, indexed pre-clear chat history is immediately ineligible for future Memory retrieval.",
  clearRetention: "Raw retained chats, saved and learned semantic facts, immutable accepted destination runs and receipts, provider-retained requests, and operator backups are not deleted or rewritten.",
  clearFuture: "Physical derivative purge continues asynchronously. The source cutoff prevents a rebuild from restoring pre-clear content; genuinely new future statements may be indexed.",
  runAction: "Review action",
  available: "Available",
  unavailable: "Unavailable",
  historyOff: "Turn on Reference chat history before running this operation.",
  historyUnavailable: "History indexing is unavailable in this installation.",
  embeddingUnavailable: "Select an available embedding deployment before re-embedding.",
  learningUnavailable: "Provider-backed Memory extraction is unavailable in this installation.",
  consentRequired: "Review the current Memory utility destinations before starting provider-backed work.",
  lexicalOnly: "No embedding deployment is selected. A normal rebuild remains lexical-only; semantic matching stays unavailable.",
  servedGeneration: "Failure or cancellation never activates the shadow generation and never implies that the current active index was replaced.",
  confirmationTitle: "Confirm history operation",
  confirmationOperation: "Operation",
  confirmationRebuild: "Build or rebuild the search index from currently eligible sources.",
  confirmationReembed: "Re-embed eligible history with the current qualified deployment and accepted destination policy.",
  confirmationRedream: "Send eligible retained source content to the configured system Memory destination for explicit reprocessing.",
  confirmationClear: "Commit the immediate retrieval fence and enqueue durable physical deletion of the admitted history-index derivatives.",
  confirmationCancel: "Cancel",
  confirmationCommit: "Confirm and start",
  admitting: "Committing operation…",
  statusHeading: "Operation status",
  clearStatusHeading: "History-index deletion",
  rebuildStatusHeading: "Rebuild job",
  progress: "Progress",
  reference: "Reference",
  updated: "Updated",
  lastAudit: "Last deletion audit",
  refresh: "Check status",
  cancelJob: "Cancel shadow job",
  cancelling: "Cancelling…",
  dismiss: "Dismiss completed status",
  dismissReference: "Dismiss saved reference",
  statePending: "Retrieval is fenced. Physical derivative deletion is queued.",
  stateClearRunning: "Retrieval is fenced. Physical derivative deletion is running.",
  stateRetry: "Retrieval stays fenced while durable deletion waits for automatic retry.",
  stateBlocked: "Retrieval stays fenced. Fast retries are exhausted; administrator attention is required and slow reconciliation continues.",
  stateClearSucceeded: "The admitted history-index derivatives passed the durable deletion audit.",
  stateQueued: "The shadow job is queued.",
  stateRebuildRunning: "The shadow operation is running while the previous generation remains active.",
  stateWaitingConsent: "The job is parked until the current Memory utility destinations are reviewed.",
  stateCatchingUp: "The shadow is catching up with current eligible sources.",
  stateReady: "The shadow is complete and waiting for the fenced activation step.",
  stateRebuildSucceeded: "The operation completed and the authoritative activation step succeeded.",
  stateFailed: "The shadow operation failed. The previous active generation remains authoritative.",
  stateStale: "The source or Memory revision changed. The stale shadow was not activated.",
  stateCancelled: "The shadow operation was cancelled. The previous active generation remains authoritative.",
  cancelBoundary: "Cancel stops only the in-progress shadow/reprocessing job. It does not switch the active generation and cannot cancel a committed deletion fence.",
  errorGeneric: "The operation did not complete. No success was assumed.",
  errorStale: "Memory changed before admission. Current settings were reloaded; review and confirm again.",
  errorConsent: "Review and accept the current Memory utility destinations before provider-backed work.",
  errorEmbedding: "The selected embedding deployment is unavailable or no longer matches current settings.",
  errorInProgress: "Another Memory rebuild or reprocessing job is already active.",
  errorConfirmation: "The exact one-time confirmation expired or did not match. Review and confirm again.",
  errorNotFound: "This saved operation reference is no longer available. No private content was returned."
} satisfies CopyLocale;

const RU = {
  entry: "Операции с историей",
  entryDescription: "Перестройте индексы, обновите производную историю или очистите индекс истории чатов.",
  title: "Операции с историей",
  back: "Назад к настройкам Памяти",
  intro: "Обслуживание производной истории Памяти без изменения исходных чатов и без преждевременного обещания завершения фоновой работы.",
  maintenanceHeading: "Обслуживание индекса",
  maintenanceDescription: "Каждая перестройка создаёт теневое поколение. Текущий активный индекс используется до успешного атомарного переключения.",
  rebuildLabel: "Построить или перестроить поисковый индекс",
  rebuildDescription: "Заново создать допустимые лексические или гибридные записи из текущего безопасного набора источников и догнать изменения перед активацией.",
  reembedLabel: "Пересчитать эмбеддинги истории",
  reembedDescription: "Создать квалифицированное гибридное теневое поколение с выбранным сейчас развёртыванием эмбеддингов.",
  redreamLabel: "Повторно обработать существующие чаты",
  redreamDescription: "Явно запустить провайдерное извлечение эпизодов из допустимых сохранённых чатов. Барьеры источников и подавления сохраняются.",
  clearHeading: "Разрушительная операция с историей",
  clearLabel: "Очистить индекс памяти истории чатов",
  clearDescription: "Оградить и удалить перестраиваемые фрагменты чатов, эпизоды и их поисковые записи.",
  clearFence: "После допуска проиндексированная до очистки история чатов немедленно исключается из будущего использования Памятью.",
  clearRetention: "Исходные сохранённые чаты, сохранённые и изученные смысловые факты, неизменяемые принятые запуски и квитанции, данные у провайдеров и резервные копии оператора не удаляются и не переписываются.",
  clearFuture: "Физическое удаление производных продолжается асинхронно. Отсечка источников не позволит перестройке вернуть старое содержимое; новые будущие утверждения можно индексировать.",
  runAction: "Проверить действие",
  available: "Доступно",
  unavailable: "Недоступно",
  historyOff: "Сначала включите использование истории чатов.",
  historyUnavailable: "Индексирование истории недоступно в этой установке.",
  embeddingUnavailable: "Перед пересчётом выберите доступное развёртывание эмбеддингов.",
  learningUnavailable: "Провайдерное извлечение Памяти недоступно в этой установке.",
  consentRequired: "Перед провайдерной операцией проверьте текущие служебные назначения Памяти.",
  lexicalOnly: "Развёртывание эмбеддингов не выбрано. Обычная перестройка останется только лексической; семантический поиск будет недоступен.",
  servedGeneration: "Ошибка или отмена никогда не активирует теневое поколение и не означает замену текущего активного индекса.",
  confirmationTitle: "Подтвердите операцию с историей",
  confirmationOperation: "Операция",
  confirmationRebuild: "Построить или перестроить поисковый индекс из допустимых сейчас источников.",
  confirmationReembed: "Пересчитать эмбеддинги допустимой истории текущим квалифицированным развёртыванием и принятой политикой назначения.",
  confirmationRedream: "Отправить допустимое содержимое сохранённых источников настроенному системному назначению Памяти для явной повторной обработки.",
  confirmationClear: "Зафиксировать немедленный барьер извлечения и поставить в очередь долговечное физическое удаление допущенных производных индекса истории.",
  confirmationCancel: "Отмена",
  confirmationCommit: "Подтвердить и запустить",
  admitting: "Фиксация операции…",
  statusHeading: "Состояние операции",
  clearStatusHeading: "Удаление индекса истории",
  rebuildStatusHeading: "Задача перестройки",
  progress: "Прогресс",
  reference: "Идентификатор",
  updated: "Обновлено",
  lastAudit: "Последний аудит удаления",
  refresh: "Проверить состояние",
  cancelJob: "Отменить теневую задачу",
  cancelling: "Отмена…",
  dismiss: "Скрыть завершённое состояние",
  dismissReference: "Убрать сохранённый идентификатор",
  statePending: "Извлечение ограждено. Физическое удаление производных поставлено в очередь.",
  stateClearRunning: "Извлечение ограждено. Выполняется физическое удаление производных.",
  stateRetry: "Извлечение остаётся ограждённым; долговечное удаление ожидает автоматического повтора.",
  stateBlocked: "Извлечение остаётся ограждённым. Быстрые повторы исчерпаны; нужен администратор, медленная сверка продолжается.",
  stateClearSucceeded: "Допущенные производные индекса истории прошли долговечный аудит удаления.",
  stateQueued: "Теневая задача поставлена в очередь.",
  stateRebuildRunning: "Теневая операция выполняется, предыдущее поколение остаётся активным.",
  stateWaitingConsent: "Задача приостановлена до проверки текущих служебных назначений Памяти.",
  stateCatchingUp: "Теневое поколение догоняет текущие допустимые источники.",
  stateReady: "Теневое поколение готово и ожидает ограждённого этапа активации.",
  stateRebuildSucceeded: "Операция завершена, авторитетный этап активации выполнен.",
  stateFailed: "Теневая операция завершилась ошибкой. Предыдущее активное поколение осталось авторитетным.",
  stateStale: "Источник или ревизия Памяти изменились. Устаревшее теневое поколение не активировано.",
  stateCancelled: "Теневая операция отменена. Предыдущее активное поколение осталось авторитетным.",
  cancelBoundary: "Отмена останавливает только выполняемую теневую или повторную обработку. Она не переключает активное поколение и не отменяет уже зафиксированный барьер удаления.",
  errorGeneric: "Операция не завершилась. Успех не был предположен.",
  errorStale: "Память изменилась до допуска. Текущие настройки загружены заново; проверьте и подтвердите ещё раз.",
  errorConsent: "Перед провайдерной работой проверьте и примите текущие служебные назначения Памяти.",
  errorEmbedding: "Выбранное развёртывание эмбеддингов недоступно или больше не соответствует текущим настройкам.",
  errorInProgress: "Другая перестройка или повторная обработка Памяти уже выполняется.",
  errorConfirmation: "Точное одноразовое подтверждение истекло или не совпало. Проверьте и подтвердите ещё раз.",
  errorNotFound: "Сохранённый идентификатор операции больше недоступен. Приватное содержимое не возвращалось."
} satisfies CopyLocale;

const COPY: Readonly<Record<MemoryUiLocale, CopyLocale>> = Object.freeze({
  EN: Object.freeze(EN),
  RU: Object.freeze(RU)
});

export function memoryOperationsUiCopy(
  locale: MemoryUiLocale,
  key: MemoryOperationsUiCopyKey
): string {
  return COPY[locale][key];
}
