export const MEMORY_OPERATIONS_UI_COPY_KEYS = [
  "entry",
  "entryDescription",
  "title",
  "back",
  "intro",
  "maintenanceHeading",
  "maintenanceDescription",
  "rebuildLabel",
  "rebuildDescription",
  "reembedLabel",
  "reembedDescription",
  "destructiveHeading",
  "destructiveDescription",
  "deletionDetails",
  "allHeading",
  "allLabel",
  "allDescription",
  "allFence",
  "allRetention",
  "allFuture",
  "learnedHeading",
  "learnedLabel",
  "learnedDescription",
  "learnedFence",
  "learnedRetention",
  "learnedFuture",
  "clearHeading",
  "clearLabel",
  "clearDescription",
  "clearFence",
  "clearRetention",
  "clearFuture",
  "runAction",
  "available",
  "unavailable",
  "historyOff",
  "historyUnavailable",
  "embeddingUnavailable",
  "consentRequired",
  "lexicalOnly",
  "servedGeneration",
  "confirmationTitle",
  "confirmationOperation",
  "confirmationRebuild",
  "confirmationReembed",
  "confirmationAll",
  "confirmationLearned",
  "confirmationClear",
  "confirmationCancel",
  "confirmationCommit",
  "admitting",
  "statusHeading",
  "allStatusHeading",
  "learnedStatusHeading",
  "clearStatusHeading",
  "rebuildStatusHeading",
  "progress",
  "reference",
  "updated",
  "lastAudit",
  "refresh",
  "cancelJob",
  "cancelling",
  "dismiss",
  "dismissReference",
  "statePending",
  "stateAllPending",
  "stateAllRunning",
  "stateAllRetry",
  "stateAllBlocked",
  "stateAllSucceeded",
  "stateLearnedRunning",
  "stateLearnedRetry",
  "stateLearnedBlocked",
  "stateLearnedSucceeded",
  "stateClearRunning",
  "stateRetry",
  "stateBlocked",
  "stateClearSucceeded",
  "stateQueued",
  "stateRebuildRunning",
  "stateWaitingConsent",
  "stateCatchingUp",
  "stateReady",
  "stateRebuildSucceeded",
  "stateFailed",
  "stateStale",
  "stateCancelled",
  "cancelBoundary",
  "errorGeneric",
  "errorStale",
  "errorConsent",
  "errorEmbedding",
  "errorInProgress",
  "errorConfirmation",
  "errorReferenceMismatch",
  "errorNotFound"
] as const;

export type MemoryOperationsUiCopyKey =
  (typeof MEMORY_OPERATIONS_UI_COPY_KEYS)[number];
type CopyLocale = Readonly<Record<MemoryOperationsUiCopyKey, string>>;

const EN = {
  entry: "Memory operations",
  entryDescription: "Rebuild indexes or delete derived Memory data.",
  title: "Memory operations",
  back: "Back to Memory settings",
  intro: "Maintain or delete derived Memory data without changing raw chats or pretending background work has already finished.",
  maintenanceHeading: "Index maintenance",
  maintenanceDescription: "Each rebuild uses a shadow generation. The currently active index remains served until an atomic successful switch.",
  rebuildLabel: "Build or rebuild search index",
  rebuildDescription: "Recreate eligible lexical or hybrid search entries from the current safe source set and catch up before activation.",
  reembedLabel: "Re-embed history index",
  reembedDescription: "Create a compatible hybrid shadow with the currently selected embedding deployment.",
  destructiveHeading: "Destructive Memory actions",
  destructiveDescription: "Each action commits an immediate retrieval fence, then proves the physical purge asynchronously.",
  deletionDetails: "What is and is not deleted",
  allHeading: "Memory reset",
  allLabel: "Delete everything Memory remembers",
  allDescription: "Turn off Memory and remove saved memories, learned details, and the chat-history index.",
  allFence: "Saved Memory, Reference chat history, and Learn automatically turn off immediately. Content created before the reset cannot be reused by Memory later.",
  allRetention: "Your raw chats remain. Text already included in accepted past answers or runs is not rewritten. Data retained by providers and operator backups outside live Memory is not deleted.",
  allFuture: "Physical deletion continues in the background. If you turn Memory back on later, only genuinely new messages created after this reset are eligible; old chats do not refill it.",
  learnedHeading: "Automatically learned memory",
  learnedLabel: "Delete automatically learned memories",
  learnedDescription: "Fence and purge automatically learned facts, candidates, evidence, feedback, and their search derivatives.",
  learnedFence: "After admission, the admitted learned facts are immediately ineligible for future Memory retrieval.",
  learnedRetention: "Explicitly saved memories, raw retained chats, immutable accepted destination runs and receipts, provider-retained requests, and operator backups are not deleted or rewritten.",
  learnedFuture: "Physical purge continues asynchronously. The source cutoff prevents old observed chat content, rebuilds, or delayed work from recreating the deleted set; genuinely new future evidence may be learned.",
  clearHeading: "Indexed chat history",
  clearLabel: "Clear chat-history memory index",
  clearDescription: "Fence and purge rebuildable chat excerpts and their search entries.",
  clearFence: "After admission, indexed pre-clear chat history is immediately ineligible for future Memory retrieval.",
  clearRetention: "Raw retained chats, saved and learned semantic facts, immutable accepted destination runs and receipts, provider-retained requests, and operator backups are not deleted or rewritten.",
  clearFuture: "Physical derivative purge continues asynchronously. The source cutoff prevents a rebuild from restoring pre-clear content; genuinely new future statements may be indexed.",
  runAction: "Review action",
  available: "Available",
  unavailable: "Unavailable",
  historyOff: "Turn on Reference chat history before running this operation.",
  historyUnavailable: "History indexing is unavailable in this installation.",
  embeddingUnavailable: "Select an available embedding deployment before re-embedding.",
  consentRequired: "Review the current Memory utility destinations before starting provider-backed work.",
  lexicalOnly: "No embedding deployment is selected. A normal rebuild remains lexical-only; semantic matching stays unavailable.",
  servedGeneration: "Failure or cancellation never activates the shadow generation and never implies that the current active index was replaced.",
  confirmationTitle: "Confirm Memory operation",
  confirmationOperation: "Operation",
  confirmationRebuild: "Build or rebuild the search index from currently eligible sources.",
  confirmationReembed: "Re-embed eligible history with the current compatible deployment and accepted destination policy.",
  confirmationAll: "Turn off Memory now and delete everything it can reuse from the admitted pre-reset set.",
  confirmationLearned: "Commit the immediate retrieval fence and enqueue durable physical deletion of the admitted automatically learned set.",
  confirmationClear: "Commit the immediate retrieval fence and enqueue durable physical deletion of the admitted history-index derivatives.",
  confirmationCancel: "Cancel",
  confirmationCommit: "Confirm and start",
  admitting: "Committing operation…",
  statusHeading: "Operation status",
  allStatusHeading: "Memory reset",
  learnedStatusHeading: "Learned-memory deletion",
  clearStatusHeading: "History-index deletion",
  rebuildStatusHeading: "Rebuild job",
  progress: "Progress",
  reference: "Reference",
  updated: "Updated",
  lastAudit: "Last deletion audit",
  refresh: "Check status",
  cancelJob: "Cancel shadow job",
  cancelling: "Cancelling…",
  dismiss: "Dismiss completed status",
  dismissReference: "Dismiss saved reference",
  statePending: "Retrieval is fenced. Physical derivative deletion is queued.",
  stateAllPending: "Memory is off. Background deletion is queued.",
  stateAllRunning: "Memory is off while its reusable data is being deleted.",
  stateAllRetry: "Memory stays off while deletion waits for an automatic retry.",
  stateAllBlocked: "Memory stays off. Fast retries are exhausted; administrator attention is required and slow reconciliation continues.",
  stateAllSucceeded: "Everything reusable by Memory passed the durable deletion audit.",
  stateLearnedRunning: "The learned set is fenced. Its physical deletion is running.",
  stateLearnedRetry: "The learned set stays fenced while durable deletion waits for automatic retry.",
  stateLearnedBlocked: "The learned set stays fenced. Fast retries are exhausted; administrator attention is required and slow reconciliation continues.",
  stateLearnedSucceeded: "The admitted learned-memory derivatives passed the durable deletion audit.",
  stateClearRunning: "Retrieval is fenced. Physical derivative deletion is running.",
  stateRetry: "Retrieval stays fenced while durable deletion waits for automatic retry.",
  stateBlocked: "Retrieval stays fenced. Fast retries are exhausted; administrator attention is required and slow reconciliation continues.",
  stateClearSucceeded: "The admitted history-index derivatives passed the durable deletion audit.",
  stateQueued: "The shadow job is queued.",
  stateRebuildRunning: "The shadow operation is running while the previous generation remains active.",
  stateWaitingConsent: "The job is parked until the current Memory utility destinations are reviewed.",
  stateCatchingUp: "The shadow is catching up with current eligible sources.",
  stateReady: "The shadow is complete and waiting for the fenced activation step.",
  stateRebuildSucceeded: "The operation completed and the authoritative activation step succeeded.",
  stateFailed: "The shadow operation failed. The previous active generation remains authoritative.",
  stateStale: "The source or Memory revision changed. The stale shadow was not activated.",
  stateCancelled: "The shadow operation was cancelled. The previous active generation remains authoritative.",
  cancelBoundary: "Cancel stops only the in-progress shadow job. It does not switch the active generation and cannot cancel a committed deletion fence.",
  errorGeneric: "The operation did not complete. No success was assumed.",
  errorStale: "Memory changed before admission. Current settings were reloaded; review and confirm again.",
  errorConsent: "Review and accept the current Memory utility destinations before provider-backed work.",
  errorEmbedding: "The selected embedding deployment is unavailable or no longer matches current settings.",
  errorInProgress: "Another Memory rebuild job is already active.",
  errorConfirmation: "The exact one-time confirmation expired or did not match. Review and confirm again.",
  errorReferenceMismatch: "The saved reference belongs to a different Memory operation and was not trusted.",
  errorNotFound: "This saved operation reference is no longer available. No private content was returned."
} satisfies CopyLocale;



export function memoryOperationsUiCopy(key: MemoryOperationsUiCopyKey): string {
  return EN[key];
}
