import type { MemoryUiLocale } from "@/lib/contracts/memory";
import { MEMORY_PRESENTATION_LOCALE } from "@/lib/contracts/memoryPresentation";

export const MEMORY_OPERATIONS_UI_COPY_KEYS = [
  "entry",
  "entryDescription",
  "title",
  "back",
  "intro",
  "maintenanceHeading",
  "maintenanceDescription",
  "rebuildLabel",
  "rebuildDescription",
  "reembedLabel",
  "reembedDescription",
  "redreamLabel",
  "redreamDescription",
  "destructiveHeading",
  "destructiveDescription",
  "deletionDetails",
  "allHeading",
  "allLabel",
  "allDescription",
  "allFence",
  "allRetention",
  "allFuture",
  "learnedHeading",
  "learnedLabel",
  "learnedDescription",
  "learnedFence",
  "learnedRetention",
  "learnedFuture",
  "clearHeading",
  "clearLabel",
  "clearDescription",
  "clearFence",
  "clearRetention",
  "clearFuture",
  "runAction",
  "available",
  "unavailable",
  "historyOff",
  "historyUnavailable",
  "embeddingUnavailable",
  "learningUnavailable",
  "consentRequired",
  "lexicalOnly",
  "servedGeneration",
  "confirmationTitle",
  "confirmationOperation",
  "confirmationRebuild",
  "confirmationReembed",
  "confirmationRedream",
  "confirmationAll",
  "confirmationLearned",
  "confirmationClear",
  "confirmationCancel",
  "confirmationCommit",
  "admitting",
  "statusHeading",
  "allStatusHeading",
  "learnedStatusHeading",
  "clearStatusHeading",
  "rebuildStatusHeading",
  "progress",
  "reference",
  "updated",
  "lastAudit",
  "refresh",
  "cancelJob",
  "cancelling",
  "dismiss",
  "dismissReference",
  "statePending",
  "stateAllPending",
  "stateAllRunning",
  "stateAllRetry",
  "stateAllBlocked",
  "stateAllSucceeded",
  "stateLearnedRunning",
  "stateLearnedRetry",
  "stateLearnedBlocked",
  "stateLearnedSucceeded",
  "stateClearRunning",
  "stateRetry",
  "stateBlocked",
  "stateClearSucceeded",
  "stateQueued",
  "stateRebuildRunning",
  "stateWaitingConsent",
  "stateCatchingUp",
  "stateReady",
  "stateRebuildSucceeded",
  "stateFailed",
  "stateStale",
  "stateCancelled",
  "cancelBoundary",
  "errorGeneric",
  "errorStale",
  "errorConsent",
  "errorEmbedding",
  "errorInProgress",
  "errorConfirmation",
  "errorReferenceMismatch",
  "errorNotFound"
] as const;

export type MemoryOperationsUiCopyKey =
  (typeof MEMORY_OPERATIONS_UI_COPY_KEYS)[number];
type CopyLocale = Readonly<Record<MemoryOperationsUiCopyKey, string>>;

const EN = {
  entry: "Memory operations",
  entryDescription: "Rebuild indexes, reprocess eligible sources, or delete derived Memory data.",
  title: "Memory operations",
  back: "Back to Memory settings",
  intro: "Maintain or delete derived Memory data without changing raw chats or pretending background work has already finished.",
  maintenanceHeading: "Index maintenance",
  maintenanceDescription: "Each rebuild uses a shadow generation. The currently active index remains served until an atomic successful switch.",
  rebuildLabel: "Build or rebuild search index",
  rebuildDescription: "Recreate eligible lexical or hybrid search entries from the current safe source set and catch up before activation.",
  reembedLabel: "Re-embed history index",
  reembedDescription: "Create a qualified hybrid shadow with the currently selected embedding deployment.",
  redreamLabel: "Reprocess existing chats",
  redreamDescription: "Explicitly run provider-backed episode extraction over eligible retained chats. Source and suppression barriers still apply.",
  destructiveHeading: "Destructive Memory actions",
  destructiveDescription: "Each action commits an immediate retrieval fence, then proves the physical purge asynchronously.",
  deletionDetails: "What is and is not deleted",
  allHeading: "Memory reset",
  allLabel: "Delete everything Memory remembers",
  allDescription: "Turn off Memory and remove saved memories, learned details, Memory summaries, and the chat-history index.",
  allFence: "Saved Memory, Reference chat history, and Learn automatically turn off immediately. Content created before the reset cannot be reused by Memory later.",
  allRetention: "Your raw chats remain. Text already included in accepted past answers or runs is not rewritten. Data retained by providers and operator backups outside live Memory is not deleted.",
  allFuture: "Physical deletion continues in the background. If you turn Memory back on later, only genuinely new messages created after this reset are eligible; old chats do not refill it.",
  learnedHeading: "Automatically learned memory",
  learnedLabel: "Delete automatically learned memories",
  learnedDescription: "Fence and purge automatically learned facts, candidates, evidence, feedback, and their search derivatives.",
  learnedFence: "After admission, the admitted learned facts are immediately ineligible for future Memory retrieval.",
  learnedRetention: "Explicitly saved memories, raw retained chats, immutable accepted destination runs and receipts, provider-retained requests, and operator backups are not deleted or rewritten.",
  learnedFuture: "Physical purge continues asynchronously. The source cutoff prevents old observed chat content, rebuilds, or delayed work from recreating the deleted set; genuinely new future evidence may be learned.",
  clearHeading: "Indexed chat history",
  clearLabel: "Clear chat-history memory index",
  clearDescription: "Fence and purge rebuildable chat excerpts, episodes, and their search entries.",
  clearFence: "After admission, indexed pre-clear chat history is immediately ineligible for future Memory retrieval.",
  clearRetention: "Raw retained chats, saved and learned semantic facts, immutable accepted destination runs and receipts, provider-retained requests, and operator backups are not deleted or rewritten.",
  clearFuture: "Physical derivative purge continues asynchronously. The source cutoff prevents a rebuild from restoring pre-clear content; genuinely new future statements may be indexed.",
  runAction: "Review action",
  available: "Available",
  unavailable: "Unavailable",
  historyOff: "Turn on Reference chat history before running this operation.",
  historyUnavailable: "History indexing is unavailable in this installation.",
  embeddingUnavailable: "Select an available embedding deployment before re-embedding.",
  learningUnavailable: "Provider-backed Memory extraction is unavailable in this installation.",
  consentRequired: "Review the current Memory utility destinations before starting provider-backed work.",
  lexicalOnly: "No embedding deployment is selected. A normal rebuild remains lexical-only; semantic matching stays unavailable.",
  servedGeneration: "Failure or cancellation never activates the shadow generation and never implies that the current active index was replaced.",
  confirmationTitle: "Confirm Memory operation",
  confirmationOperation: "Operation",
  confirmationRebuild: "Build or rebuild the search index from currently eligible sources.",
  confirmationReembed: "Re-embed eligible history with the current qualified deployment and accepted destination policy.",
  confirmationRedream: "Send eligible retained source content to the configured system Memory destination for explicit reprocessing.",
  confirmationAll: "Turn off Memory now and delete everything it can reuse from the admitted pre-reset set.",
  confirmationLearned: "Commit the immediate retrieval fence and enqueue durable physical deletion of the admitted automatically learned set.",
  confirmationClear: "Commit the immediate retrieval fence and enqueue durable physical deletion of the admitted history-index derivatives.",
  confirmationCancel: "Cancel",
  confirmationCommit: "Confirm and start",
  admitting: "Committing operation…",
  statusHeading: "Operation status",
  allStatusHeading: "Memory reset",
  learnedStatusHeading: "Learned-memory deletion",
  clearStatusHeading: "History-index deletion",
  rebuildStatusHeading: "Rebuild job",
  progress: "Progress",
  reference: "Reference",
  updated: "Updated",
  lastAudit: "Last deletion audit",
  refresh: "Check status",
  cancelJob: "Cancel shadow job",
  cancelling: "Cancelling…",
  dismiss: "Dismiss completed status",
  dismissReference: "Dismiss saved reference",
  statePending: "Retrieval is fenced. Physical derivative deletion is queued.",
  stateAllPending: "Memory is off. Background deletion is queued.",
  stateAllRunning: "Memory is off while its reusable data is being deleted.",
  stateAllRetry: "Memory stays off while deletion waits for an automatic retry.",
  stateAllBlocked: "Memory stays off. Fast retries are exhausted; administrator attention is required and slow reconciliation continues.",
  stateAllSucceeded: "Everything reusable by Memory passed the durable deletion audit.",
  stateLearnedRunning: "The learned set is fenced. Its physical deletion is running.",
  stateLearnedRetry: "The learned set stays fenced while durable deletion waits for automatic retry.",
  stateLearnedBlocked: "The learned set stays fenced. Fast retries are exhausted; administrator attention is required and slow reconciliation continues.",
  stateLearnedSucceeded: "The admitted learned-memory derivatives passed the durable deletion audit.",
  stateClearRunning: "Retrieval is fenced. Physical derivative deletion is running.",
  stateRetry: "Retrieval stays fenced while durable deletion waits for automatic retry.",
  stateBlocked: "Retrieval stays fenced. Fast retries are exhausted; administrator attention is required and slow reconciliation continues.",
  stateClearSucceeded: "The admitted history-index derivatives passed the durable deletion audit.",
  stateQueued: "The shadow job is queued.",
  stateRebuildRunning: "The shadow operation is running while the previous generation remains active.",
  stateWaitingConsent: "The job is parked until the current Memory utility destinations are reviewed.",
  stateCatchingUp: "The shadow is catching up with current eligible sources.",
  stateReady: "The shadow is complete and waiting for the fenced activation step.",
  stateRebuildSucceeded: "The operation completed and the authoritative activation step succeeded.",
  stateFailed: "The shadow operation failed. The previous active generation remains authoritative.",
  stateStale: "The source or Memory revision changed. The stale shadow was not activated.",
  stateCancelled: "The shadow operation was cancelled. The previous active generation remains authoritative.",
  cancelBoundary: "Cancel stops only the in-progress shadow/reprocessing job. It does not switch the active generation and cannot cancel a committed deletion fence.",
  errorGeneric: "The operation did not complete. No success was assumed.",
  errorStale: "Memory changed before admission. Current settings were reloaded; review and confirm again.",
  errorConsent: "Review and accept the current Memory utility destinations before provider-backed work.",
  errorEmbedding: "The selected embedding deployment is unavailable or no longer matches current settings.",
  errorInProgress: "Another Memory rebuild or reprocessing job is already active.",
  errorConfirmation: "The exact one-time confirmation expired or did not match. Review and confirm again.",
  errorReferenceMismatch: "The saved reference belongs to a different Memory operation and was not trusted.",
  errorNotFound: "This saved operation reference is no longer available. No private content was returned."
} satisfies CopyLocale;

const RU = {
  entry: "Операции Памяти",
  entryDescription: "Перестройте индексы, повторно обработайте допустимые источники или удалите производные данные Памяти.",
  title: "Операции Памяти",
  back: "Назад к настройкам Памяти",
  intro: "Обслуживание и удаление производных данных Памяти без изменения исходных чатов и без преждевременного обещания завершения фоновой работы.",
  maintenanceHeading: "Обслуживание индекса",
  maintenanceDescription: "Каждая перестройка создаёт теневое поколение. Текущий активный индекс используется до успешного атомарного переключения.",
  rebuildLabel: "Построить или перестроить поисковый индекс",
  rebuildDescription: "Заново создать допустимые лексические или гибридные записи из текущего безопасного набора источников и догнать изменения перед активацией.",
  reembedLabel: "Пересчитать эмбеддинги истории",
  reembedDescription: "Создать квалифицированное гибридное теневое поколение с выбранным сейчас развёртыванием эмбеддингов.",
  redreamLabel: "Повторно обработать существующие чаты",
  redreamDescription: "Явно запустить провайдерное извлечение эпизодов из допустимых сохранённых чатов. Барьеры источников и подавления сохраняются.",
  destructiveHeading: "Разрушительные операции Памяти",
  destructiveDescription: "Каждая операция немедленно фиксирует барьер извлечения, а затем асинхронно доказывает физическое удаление.",
  deletionDetails: "Что удаляется, а что сохраняется",
  allHeading: "Сброс Памяти",
  allLabel: "Удалить всё, что запомнила Память",
  allDescription: "Отключить Память и удалить сохранённые воспоминания, изученные сведения, сводку и индекс истории чатов.",
  allFence: "Сохранённая Память, использование истории чатов и автоматическое запоминание отключатся сразу. Память не сможет позднее повторно использовать содержимое, созданное до сброса.",
  allRetention: "Исходные чаты останутся. Текст, уже попавший в принятые прошлые ответы или запуски, не переписывается. Данные у провайдеров и резервные копии оператора вне активной Памяти не удаляются.",
  allFuture: "Физическое удаление продолжится в фоне. Если позднее снова включить Память, подойдут только действительно новые сообщения после этого сброса; старые чаты не заполнят её заново.",
  learnedHeading: "Автоматически изученная память",
  learnedLabel: "Удалить автоматически изученные воспоминания",
  learnedDescription: "Оградить и удалить автоматически изученные факты, кандидаты, свидетельства, отзывы и их поисковые производные.",
  learnedFence: "После допуска выбранные изученные факты немедленно исключаются из будущего использования Памятью.",
  learnedRetention: "Явно сохранённые воспоминания, исходные сохранённые чаты, неизменяемые принятые запуски и квитанции, данные у провайдеров и резервные копии оператора не удаляются и не переписываются.",
  learnedFuture: "Физическое удаление продолжается асинхронно. Отсечка источников не позволит старому содержимому чатов, перестройке или запоздалой задаче восстановить удалённый набор; действительно новые будущие свидетельства можно изучить.",
  clearHeading: "Проиндексированная история чатов",
  clearLabel: "Очистить индекс памяти истории чатов",
  clearDescription: "Оградить и удалить перестраиваемые фрагменты чатов, эпизоды и их поисковые записи.",
  clearFence: "После допуска проиндексированная до очистки история чатов немедленно исключается из будущего использования Памятью.",
  clearRetention: "Исходные сохранённые чаты, сохранённые и изученные смысловые факты, неизменяемые принятые запуски и квитанции, данные у провайдеров и резервные копии оператора не удаляются и не переписываются.",
  clearFuture: "Физическое удаление производных продолжается асинхронно. Отсечка источников не позволит перестройке вернуть старое содержимое; новые будущие утверждения можно индексировать.",
  runAction: "Проверить действие",
  available: "Доступно",
  unavailable: "Недоступно",
  historyOff: "Сначала включите использование истории чатов.",
  historyUnavailable: "Индексирование истории недоступно в этой установке.",
  embeddingUnavailable: "Перед пересчётом выберите доступное развёртывание эмбеддингов.",
  learningUnavailable: "Провайдерное извлечение Памяти недоступно в этой установке.",
  consentRequired: "Перед провайдерной операцией проверьте текущие служебные назначения Памяти.",
  lexicalOnly: "Развёртывание эмбеддингов не выбрано. Обычная перестройка останется только лексической; семантический поиск будет недоступен.",
  servedGeneration: "Ошибка или отмена никогда не активирует теневое поколение и не означает замену текущего активного индекса.",
  confirmationTitle: "Подтвердите операцию Памяти",
  confirmationOperation: "Операция",
  confirmationRebuild: "Построить или перестроить поисковый индекс из допустимых сейчас источников.",
  confirmationReembed: "Пересчитать эмбеддинги допустимой истории текущим квалифицированным развёртыванием и принятой политикой назначения.",
  confirmationRedream: "Отправить допустимое содержимое сохранённых источников настроенному системному назначению Памяти для явной повторной обработки.",
  confirmationAll: "Сразу отключить Память и удалить всё, что она может повторно использовать из набора до сброса.",
  confirmationLearned: "Зафиксировать немедленный барьер извлечения и поставить в очередь долговечное физическое удаление допущенного набора автоматически изученных данных.",
  confirmationClear: "Зафиксировать немедленный барьер извлечения и поставить в очередь долговечное физическое удаление допущенных производных индекса истории.",
  confirmationCancel: "Отмена",
  confirmationCommit: "Подтвердить и запустить",
  admitting: "Фиксация операции…",
  statusHeading: "Состояние операции",
  allStatusHeading: "Сброс Памяти",
  learnedStatusHeading: "Удаление изученных воспоминаний",
  clearStatusHeading: "Удаление индекса истории",
  rebuildStatusHeading: "Задача перестройки",
  progress: "Прогресс",
  reference: "Идентификатор",
  updated: "Обновлено",
  lastAudit: "Последний аудит удаления",
  refresh: "Проверить состояние",
  cancelJob: "Отменить теневую задачу",
  cancelling: "Отмена…",
  dismiss: "Скрыть завершённое состояние",
  dismissReference: "Убрать сохранённый идентификатор",
  statePending: "Извлечение ограждено. Физическое удаление производных поставлено в очередь.",
  stateAllPending: "Память отключена. Фоновое удаление поставлено в очередь.",
  stateAllRunning: "Память отключена, её повторно используемые данные удаляются.",
  stateAllRetry: "Память остаётся отключённой, пока удаление ожидает автоматического повтора.",
  stateAllBlocked: "Память остаётся отключённой. Быстрые повторы исчерпаны; нужен администратор, медленная сверка продолжается.",
  stateAllSucceeded: "Все данные, которые могла повторно использовать Память, прошли долговечный аудит удаления.",
  stateLearnedRunning: "Изученный набор ограждён. Выполняется его физическое удаление.",
  stateLearnedRetry: "Изученный набор остаётся ограждённым; долговечное удаление ожидает автоматического повтора.",
  stateLearnedBlocked: "Изученный набор остаётся ограждённым. Быстрые повторы исчерпаны; нужен администратор, медленная сверка продолжается.",
  stateLearnedSucceeded: "Допущенные производные изученной памяти прошли долговечный аудит удаления.",
  stateClearRunning: "Извлечение ограждено. Выполняется физическое удаление производных.",
  stateRetry: "Извлечение остаётся ограждённым; долговечное удаление ожидает автоматического повтора.",
  stateBlocked: "Извлечение остаётся ограждённым. Быстрые повторы исчерпаны; нужен администратор, медленная сверка продолжается.",
  stateClearSucceeded: "Допущенные производные индекса истории прошли долговечный аудит удаления.",
  stateQueued: "Теневая задача поставлена в очередь.",
  stateRebuildRunning: "Теневая операция выполняется, предыдущее поколение остаётся активным.",
  stateWaitingConsent: "Задача приостановлена до проверки текущих служебных назначений Памяти.",
  stateCatchingUp: "Теневое поколение догоняет текущие допустимые источники.",
  stateReady: "Теневое поколение готово и ожидает ограждённого этапа активации.",
  stateRebuildSucceeded: "Операция завершена, авторитетный этап активации выполнен.",
  stateFailed: "Теневая операция завершилась ошибкой. Предыдущее активное поколение осталось авторитетным.",
  stateStale: "Источник или ревизия Памяти изменились. Устаревшее теневое поколение не активировано.",
  stateCancelled: "Теневая операция отменена. Предыдущее активное поколение осталось авторитетным.",
  cancelBoundary: "Отмена останавливает только выполняемую теневую или повторную обработку. Она не переключает активное поколение и не отменяет уже зафиксированный барьер удаления.",
  errorGeneric: "Операция не завершилась. Успех не был предположен.",
  errorStale: "Память изменилась до допуска. Текущие настройки загружены заново; проверьте и подтвердите ещё раз.",
  errorConsent: "Перед провайдерной работой проверьте и примите текущие служебные назначения Памяти.",
  errorEmbedding: "Выбранное развёртывание эмбеддингов недоступно или больше не соответствует текущим настройкам.",
  errorInProgress: "Другая перестройка или повторная обработка Памяти уже выполняется.",
  errorConfirmation: "Точное одноразовое подтверждение истекло или не совпало. Проверьте и подтвердите ещё раз.",
  errorReferenceMismatch: "Сохранённый идентификатор относится к другой операции Памяти и не был принят как достоверный.",
  errorNotFound: "Сохранённый идентификатор операции больше недоступен. Приватное содержимое не возвращалось."
} satisfies CopyLocale;

const COPY: Readonly<Record<MemoryUiLocale, CopyLocale>> = Object.freeze({
  EN: Object.freeze(EN),
  RU: Object.freeze(RU)
});

export function memoryOperationsUiCopy(
  _locale: MemoryUiLocale,
  key: MemoryOperationsUiCopyKey
): string {
  return COPY[MEMORY_PRESENTATION_LOCALE][key];
}
