import type { MemoryUiLocale } from "@/lib/contracts/memory";

export const MEMORY_HISTORY_UI_COPY_KEYS = [
  "entry",
  "entryDescription",
  "title",
  "back",
  "intro",
  "queryLabel",
  "queryPlaceholder",
  "search",
  "filters",
  "chat",
  "allChats",
  "folder",
  "allFolders",
  "fromDate",
  "throughDate",
  "dateHelp",
  "loading",
  "cancel",
  "cancelled",
  "error",
  "retry",
  "queryInvalid",
  "intervalInvalid",
  "empty",
  "loadMore",
  "loadingMore",
  "openChat",
  "openArchived",
  "archived",
  "sourceTrail",
  "excerpt",
  "episode",
  "lexicalReady",
  "vectorReady",
  "vectorNotConfigured",
  "vectorUnavailable",
  "vectorStale",
  "vectorProfileUnsupported",
  "indexUnavailable",
  "historyDisabled",
  "itemLexical",
  "itemVectorPending",
  "itemHybrid",
  "itemDegraded"
] as const;

export type MemoryHistoryUiCopyKey = (typeof MEMORY_HISTORY_UI_COPY_KEYS)[number];
type MemoryHistoryUiCopyLocale = Readonly<Record<MemoryHistoryUiCopyKey, string>>;

const EN = {
  entry: "Search chat history",
  entryDescription: "Recover an earlier passage or decision from eligible retained chats.",
  title: "Search chat history",
  back: "Back to saved memories",
  intro: "Search safe Memory excerpts and episodes. This is separate from workspace and sidebar search.",
  queryLabel: "History search",
  queryPlaceholder: "Decision, passage, or earlier context",
  search: "Search history",
  filters: "Limit the source trail",
  chat: "Chat",
  allChats: "All eligible chats",
  folder: "Folder",
  allFolders: "All eligible folders",
  fromDate: "From date",
  throughDate: "Through date",
  dateHelp: "Dates use UTC calendar days; the through date is included.",
  loading: "Searching eligible history…",
  cancel: "Cancel search",
  cancelled: "Search cancelled. Your query and filters are still here.",
  error: "History search could not be completed.",
  retry: "Retry search",
  queryInvalid: "Enter a non-blank query of 500 characters or fewer.",
  intervalInvalid: "Choose a valid date range with the start no later than the through date.",
  empty: "No eligible retained history matches this search.",
  loadMore: "Load more history",
  loadingMore: "Loading more history…",
  openChat: "Open chat",
  openArchived: "Open archived preview",
  archived: "Archived source",
  sourceTrail: "Source trail",
  excerpt: "Chat excerpt",
  episode: "Conversation episode",
  lexicalReady: "Lexical search is active.",
  vectorReady: "Semantic and lexical search are active.",
  vectorNotConfigured: "Lexical search is active; semantic matching is not configured.",
  vectorUnavailable: "Lexical results are shown; semantic matching is temporarily unavailable.",
  vectorStale: "Lexical results are shown; semantic vectors are being refreshed.",
  vectorProfileUnsupported: "Lexical results are shown; this vector profile is unsupported.",
  indexUnavailable: "The retained-history index is currently unavailable.",
  historyDisabled: "Chat-history reference is off. Turn it on in Memory settings to search retained history.",
  itemLexical: "Lexical index ready",
  itemVectorPending: "Vector index pending",
  itemHybrid: "Lexical and vector indexes ready",
  itemDegraded: "Fallback index only"
} satisfies MemoryHistoryUiCopyLocale;

const RU = {
  entry: "Поиск по истории чатов",
  entryDescription: "Найдите прежний фрагмент или решение в допустимых сохранённых чатах.",
  title: "Поиск по истории чатов",
  back: "Назад к сохранённым воспоминаниям",
  intro: "Поиск по безопасным фрагментам и эпизодам Памяти. Он не связан с поиском в боковой панели.",
  queryLabel: "Поиск по истории",
  queryPlaceholder: "Решение, фрагмент или прежний контекст",
  search: "Найти в истории",
  filters: "Ограничить источники",
  chat: "Чат",
  allChats: "Все допустимые чаты",
  folder: "Папка",
  allFolders: "Все допустимые папки",
  fromDate: "Начиная с даты",
  throughDate: "По дату включительно",
  dateHelp: "Используются календарные дни UTC; конечная дата включена.",
  loading: "Поиск по допустимой истории…",
  cancel: "Отменить поиск",
  cancelled: "Поиск отменён. Запрос и фильтры сохранены.",
  error: "Не удалось выполнить поиск по истории.",
  retry: "Повторить поиск",
  queryInvalid: "Введите непустой запрос длиной не более 500 символов.",
  intervalInvalid: "Выберите корректный диапазон: начало не позже конечной даты.",
  empty: "В допустимой сохранённой истории ничего не найдено.",
  loadMore: "Загрузить ещё из истории",
  loadingMore: "Загрузка истории…",
  openChat: "Открыть чат",
  openArchived: "Открыть архивный просмотр",
  archived: "Источник в архиве",
  sourceTrail: "След источника",
  excerpt: "Фрагмент чата",
  episode: "Эпизод разговора",
  lexicalReady: "Лексический поиск активен.",
  vectorReady: "Семантический и лексический поиск активны.",
  vectorNotConfigured: "Лексический поиск активен; семантическое сопоставление не настроено.",
  vectorUnavailable: "Показаны лексические результаты; семантическое сопоставление временно недоступно.",
  vectorStale: "Показаны лексические результаты; семантические векторы обновляются.",
  vectorProfileUnsupported: "Показаны лексические результаты; этот векторный профиль не поддерживается.",
  indexUnavailable: "Индекс сохранённой истории сейчас недоступен.",
  historyDisabled: "Использование истории чатов выключено. Включите его в настройках Памяти для поиска.",
  itemLexical: "Лексический индекс готов",
  itemVectorPending: "Векторный индекс ожидается",
  itemHybrid: "Лексический и векторный индексы готовы",
  itemDegraded: "Только резервный индекс"
} satisfies MemoryHistoryUiCopyLocale;

const COPY: Readonly<Record<MemoryUiLocale, MemoryHistoryUiCopyLocale>> =
  Object.freeze({ EN: Object.freeze(EN), RU: Object.freeze(RU) });

export function memoryHistoryUiCopy(
  locale: MemoryUiLocale,
  key: MemoryHistoryUiCopyKey
): string {
  return COPY[locale][key];
}
